console.log("1"+2)
console.log(1+"2")
console.log("1"+2+2)
console.log(1+2+"2")
console.log(true)
console.log(1+true)
// console.log(true+) this throws an error
console.log(1+false)
console.log(false+1)
console.log(false+true)
console.log(true+true)
console.log(true+false)
console.log(false+false)
console.log(null+1)
console.log(1+true+2)
console.log(+"")